### ISSUE TITLE
Getting a parsing error

### ISSUE THREAD

**Issue by jkretsch** [fergalgribben/jenkinsxml2jobdsl#2]
Getting this error ...
org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.PositionalXMLReader.readXML(PositionalXMLReader.java:87)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.DocumentFactory.getXmlAsDocument(DocumentFactory.java:17)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.determineProjectType(Parser.java:44)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.createUnmarshaller(Parser.java:82)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.configXMLToProject(Parser.java:55)
        at com.fergalgribben.jenkinsxml2jobdsl.ProjectConvertor.convert(ProjectConvertor.java:42)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.convertProjectsUsingCommandLineArgs(CLI.java:83)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.processCommandLineArgs(CLI.java:62)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.parse(CLI.java:40)
        at com.fergalgribben.jenkinsxml2jobdsl.Main.main(Main.java:14)
Exception in thread "main" java.lang.NullPointerException
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.determineProjectType(Parser.java:44)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.createUnmarshaller(Parser.java:82)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.configXMLToProject(Parser.java:55)
        at com.fergalgribben.jenkinsxml2jobdsl.ProjectConvertor.convert(ProjectConvertor.java:42)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.convertProjectsUsingCommandLineArgs(CLI.java:83)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.processCommandLineArgs(CLI.java:62)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.parse(CLI.java:40)
        at com.fergalgribben.jenkinsxml2jobdsl.Main.main(Main.java:14)

**Comment by fergalgribben** [comment]
@jkretsch hey, thanks for checking out this project! Can you tell me how you ran the convertor to get this error, i.e. what flags did you pass, and also, are you able to send me a copy of the problematic XML? Thanks

**Comment by jkretsch** [comment]
Here's my command line (I didn't include the entire jenkins api token) ... C:\Users\johnkr\git\jenkinsxml2jobdsl>java -jar build/libs/jenkinsxml2jobdsl.jar -u johnkr -a 52233232... -j jenkinsmm.vspglobal.
com -p 443 eligibility-web-performance-average

**Comment by fergalgribben** [comment]
@jkretsch thanks for this. Are you able to paste the contents of http://jenkinsmm.vspglobal:443/job/eligibility-web-performance-average/config.xml? You can remove any sensitive data, it's just to get an idea of the structure of the config, thanks!

**Comment by jkretsch** [comment]
[config.txt](https://github.com/fergalgribben/jenkinsxml2jobdsl/files/2337553/config.txt)

**Comment by fergalgribben** [comment]
@jkretsch so I created a dummy job on my local jenkins instance (jenkins.war version 2.121.3 on OS X), and I modified the config.xml on disk to reflect the config you posted, and I was able to generate a job DSL script (attached). Since I didn't encounter the same issue as you, I'm wondering if this issue is specific to Windows...I don't have a Windows box to test on, so I'm afraid I wouldn't be able to test for that effectively. Other than that, what version of Jenkins are you running? Are you using the standalone .war file, or did you use an installer for your OS?
[jkretsch.groovy.txt](https://github.com/fergalgribben/jenkinsxml2jobdsl/files/2337670/jkretsch.groovy.txt)

**Comment by jkretsch** [comment]
Initially, I was trying this on our corporate Jenkins multimaster.  However, now I’ve fired up a local Jenkins instance.  I create a new freestyle project and didn’t make any changes to the configuration.  I ran the converter and it worked.  Then I created another new project but this time I selected the Maven project option.  Now when I run the converter I get this error …

C:\Users\johnkr\git\jenkinsxml2jobdsl>java -jar build/libs/jenkinsxml2jobdsl.jar -u johnkr -a 1135359decfae6e2a0737b03beca5435ce -j localhost -p 8080
TestProjectMaven
Exception in thread "main" java.lang.NullPointerException
        at com.fergalgribben.jenkinsxml2jobdsl.xml.model.project.MavenProject.build(MavenProject.java:36)
        at com.fergalgribben.jenkinsxml2jobdsl.jobdsl.DSLBuilder.build(DSLBuilder.java:18)
        at com.fergalgribben.jenkinsxml2jobdsl.ProjectConvertor.convert(ProjectConvertor.java:44)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.convertProjectsUsingCommandLineArgs(CLI.java:83)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.processCommandLineArgs(CLI.java:62)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.parse(CLI.java:40)
        at com.fergalgribben.jenkinsxml2jobdsl.Main.main(Main.java:14)

**Comment by jkretsch** [comment]
Hi,

I’m just about to leave the office and I’ll be out for 4 days.  I’ll get back to this when I return.

-John

**Comment by jkretsch** [comment]
I pulled the latest change and rebuilt and now it’s working with the Maven project on my local Jenkins.  However, I’m still unable to get it to work on our corporate Jenkins.  The corporate Jenkins uses is a Jenkins multimaster environment so the path to the project is something like http://jenkinsmm.vspglobal.com/<project<http://jenkinsmm.vspglobal.com/%3cproject> name>/job/<job name>.  Here’s the error message …

org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.PositionalXMLReader.readXML(PositionalXMLReader.java:87)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.DocumentFactory.getXmlAsDocument(DocumentFactory.java:17)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.determineProjectType(Parser.java:44)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.createUnmarshaller(Parser.java:82)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.configXMLToProject(Parser.java:55)
        at com.fergalgribben.jenkinsxml2jobdsl.ProjectConvertor.convert(ProjectConvertor.java:42)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.convertProjectsUsingCommandLineArgs(CLI.java:83)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.processCommandLineArgs(CLI.java:62)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.parse(CLI.java:40)
        at com.fergalgribben.jenkinsxml2jobdsl.Main.main(Main.java:14)
Exception in thread "main" java.lang.NullPointerException
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.determineProjectType(Parser.java:44)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.createUnmarshaller(Parser.java:82)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.configXMLToProject(Parser.java:55)
        at com.fergalgribben.jenkinsxml2jobdsl.ProjectConvertor.convert(ProjectConvertor.java:42)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.convertProjectsUsingCommandLineArgs(CLI.java:83)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.processCommandLineArgs(CLI.java:62)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.parse(CLI.java:40)
        at com.fergalgribben.jenkinsxml2jobdsl.Main.main(Main.java:14)

**Comment by jkretsch** [comment]
I did some additional testing and the job converter works fine with our community Jenkins where the job path is <server>/job/<job name>.  However, with our multimaster Jenkins where the job path is <server>/<project>/job/<job name> I get a “404 not found” error.

From: John Kretschmann
Sent: Tuesday, September 04, 2018 12:49 PM
To: 'fergalgribben/jenkinsxml2jobdsl' <reply@reply.github.com>; fergalgribben/jenkinsxml2jobdsl <jenkinsxml2jobdsl@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [fergalgribben/jenkinsxml2jobdsl] Getting a parsing error (#2)

I pulled the latest change and rebuilt and now it’s working with the Maven project on my local Jenkins.  However, I’m still unable to get it to work on our corporate Jenkins.  The corporate Jenkins uses is a Jenkins multimaster environment so the path to the project is something like http://jenkinsmm.vspglobal.com/<project<http://jenkinsmm.vspglobal.com/%3cproject> name>/job/<job name>.  Here’s the error message …

org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.PositionalXMLReader.readXML(PositionalXMLReader.java:87)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.DocumentFactory.getXmlAsDocument(DocumentFactory.java:17)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.determineProjectType(Parser.java:44)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.createUnmarshaller(Parser.java:82)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.configXMLToProject(Parser.java:55)
        at com.fergalgribben.jenkinsxml2jobdsl.ProjectConvertor.convert(ProjectConvertor.java:42)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.convertProjectsUsingCommandLineArgs(CLI.java:83)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.processCommandLineArgs(CLI.java:62)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.parse(CLI.java:40)
        at com.fergalgribben.jenkinsxml2jobdsl.Main.main(Main.java:14)
Exception in thread "main" java.lang.NullPointerException
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.determineProjectType(Parser.java:44)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.createUnmarshaller(Parser.java:82)
        at com.fergalgribben.jenkinsxml2jobdsl.xml.Parser.configXMLToProject(Parser.java:55)
        at com.fergalgribben.jenkinsxml2jobdsl.ProjectConvertor.convert(ProjectConvertor.java:42)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.convertProjectsUsingCommandLineArgs(CLI.java:83)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.processCommandLineArgs(CLI.java:62)
        at com.fergalgribben.jenkinsxml2jobdsl.CLI.parse(CLI.java:40)
        at com.fergalgribben.jenkinsxml2jobdsl.Main.main(Main.java:14)

**Comment by fergalgribben** [comment]
@jkretsch sorry for the delay, can you pull the latest and rebuild and try again? I've added a -r flag which will let you specify the project name. Thanks!

**Comment by jkretsch** [comment]
Looks like that worked.  Here’s my command line (with partial API token) …

java -jar build/libs/jenkinsxml2jobdsl.jar -u johnkr -a f55331093… -j jenkinsmm.vspglobal.com -r testengineers -p 80 MavenTestProject

I haven’t tried to run the DSL script to see if it actually works but at least the converter is running with no errors.
